version: 2

builds:
  - binary: md365
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  disable: true

release:
  header: "{{ .TagBody }}"

brews:
  - repository:
      owner: lcorneliussen
      name: homebrew-md365
    homepage: https://github.com/lcorneliussen/md365
    description: "AI-native CLI for Microsoft 365 - calendars, contacts, and mail as Markdown"
    license: MIT
    install: |
      bin.install "md365"
    test: |
      system "#{bin}/md365", "--help"
